modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory T
license = "${mod_license}"
issueTrackerURL="https://github.com/JustAHuman-xD/VaultHuntersExtraRules/issues" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL="https://github.com/JustAHuman-xD/VaultHuntersExtraRules" #optional
#logoFile="kendrome_vh_tweaks.png" #optional
credits="JustAHuman-xD" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''

[[dependencies.${ mod_id }]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "the_vault"
mandatory = true
versionRange = "[1.18.2-3.11.0.2514,)"
ordering = "AFTER"
side = "SERVER"